"""Generates infra/prometheus/rules/slo-recording.yml and slo-burn-alerts.yml.

Usage: python3 infra/prometheus/gen_slo_rules.py infra/prometheus/rules
Keep in sync with docs/SLO.md."""
import sys

OUT = sys.argv[1]
RB = "https://github.com/soumadipcodeEnthusiast/ai-driven-event-processing-system/blob/main/docs/runbooks/"

# slo id, service, objective, error-numerator(W), total(W), description, req
SLOS = [
    ("ingestion-availability", "ingestion-service", 0.999,
     'sum(rate(ingestion_events_total{outcome="error"}[W]))',
     'sum(rate(ingestion_events_total[W]))',
     "events consumed without an unexpected processing error (outcome!=error)", "REQ-A/REQ-B"),
    ("ingestion-latency", "ingestion-service", 0.99,
     '(sum(rate(ingestion_processing_seconds_count[W])) - sum(rate(ingestion_processing_seconds_bucket{le="0.5"}[W])))',
     'sum(rate(ingestion_processing_seconds_count[W]))',
     "events processed in < 500 ms", "REQ-A"),
    ("forecast-availability", "forecasting-service", 0.99,
     'sum(rate(forecast_runs_total{outcome="error"}[W]))',
     'sum(rate(forecast_runs_total[W]))',
     "forecast runs that complete with outcome=ok", "REQ-D/REQ-E"),
    ("forecast-latency", "forecasting-service", 0.99,
     '(sum(rate(forecast_latency_seconds_count[W])) - sum(rate(forecast_latency_seconds_bucket{le=~"2|2\\\\.0"}[W])))',
     'sum(rate(forecast_latency_seconds_count[W]))',
     "forecasts (60-min window) completed in < 2 s", "REQ-D"),
    ("diagnosis-availability", "diagnostic-service", 0.99,
     'sum(rate(diagnoses_total{outcome="error"}[W]))',
     'sum(rate(diagnoses_total[W]))',
     "diagnoses that return a playbook (ok or fallback)", "REQ-H/REQ-I"),
    ("graph-context-latency", "diagnostic-service", 0.99,
     '(sum(rate(graph_context_seconds_count[W])) - sum(rate(graph_context_seconds_bucket{le=~"1|1\\\\.0"}[W])))',
     'sum(rate(graph_context_seconds_count[W]))',
     "2-hop graph context lookups completed in < 1 s", "REQ-G"),
]
WINDOWS = ["5m", "30m", "1h", "2h", "6h", "1d", "3d", "30d"]

rec = ["# GENERATED by infra/prometheus/gen_slo_rules.py (python3 infra/prometheus/gen_slo_rules.py infra/prometheus/rules) — do not edit by hand — SLO recording rules.",
       "# SLO definitions: docs/SLO.md. Naming: level:metric:operation (Prometheus conventions).",
       "#   slo:objective:ratio{slo,service}            target (e.g. 0.999)",
       "#   slo:sli_error:ratio_rate<W>{slo,service}     bad/total over window W",
       "#   slo:error_budget:remaining_ratio{slo,service} 1 - consumed budget over 30d (can go < 0)",
       "#   slo:burn_rate:ratio_rate1h{slo,service}      error ratio / (1 - objective)",
       "groups:"]
rec.append("  - name: slo-objectives")
rec.append("    interval: 1m")
rec.append("    rules:")
for slo, svc, obj, *_ in SLOS:
    rec += [f"      - record: slo:objective:ratio",
            f"        expr: vector({obj})",
            f"        labels: {{slo: {slo}, service: {svc}}}"]
rec += ["      - record: slo:objective:ratio",
        "        expr: vector(0.995)",
        "        labels: {slo: service-availability, service: all}"]

for slo, svc, obj, bad, total, desc, req in SLOS:
    rec.append(f"  - name: slo-{slo}")
    rec.append(f"    # {req}: {desc}; objective {obj*100:g}% over 30d")
    rec.append("    rules:")
    for w in WINDOWS:
        b, t = bad.replace("[W]", f"[{w}]"), total.replace("[W]", f"[{w}]")
        rec += [f"      - record: slo:sli_error:ratio_rate{w}",
                f"        expr: |",
                f"          {b}",
                f"          /",
                f"          {t}",
                f"        labels: {{slo: {slo}, service: {svc}}}"]
rec.append("  - name: slo-service-availability")
rec.append("    # Scrape availability (up) of the three application services; objective 99.5% over 30d")
rec.append("    rules:")
for w in ["5m", "1h", "1d", "30d"]:
    rec += [f"      - record: service:up:avg_over_time{w}",
            f"        expr: avg by (service) (avg_over_time(up{{job=~\"ingestion-service|forecasting-service|diagnostic-service\"}}[{w}]))"]
rec += ["      - record: slo:sli_error:ratio_rate30d",
        "        expr: 1 - avg(service:up:avg_over_time30d)",
        "        labels: {slo: service-availability, service: all}"]
rec.append("  - name: slo-error-budget")
rec.append("    interval: 1m")
rec.append("    rules:")
rec += ["      - record: slo:error_budget:remaining_ratio",
        "        expr: 1 - (slo:sli_error:ratio_rate30d / on (slo, service) (1 - slo:objective:ratio))",
        "      - record: slo:burn_rate:ratio_rate1h",
        "        expr: slo:sli_error:ratio_rate1h / on (slo, service) (1 - slo:objective:ratio)",
        "      - record: slo:burn_rate:ratio_rate6h",
        "        expr: slo:sli_error:ratio_rate6h / on (slo, service) (1 - slo:objective:ratio)",
        "      - record: slo:burn_rate:ratio_rate3d",
        "        expr: slo:sli_error:ratio_rate3d / on (slo, service) (1 - slo:objective:ratio)"]
open(f"{OUT}/slo-recording.yml", "w").write("\n".join(rec) + "\n")

# ── multi-window multi-burn-rate alerts (Google SRE workbook, ch. 5) ──
BURN = {  # alertname -> slo
    "IngestionErrorBudgetBurn": ("ingestion-availability", "ingestion-error-budget-burn",
                                 "Ingestion is burning its availability error budget (events ending in outcome=error)"),
    "IngestionLatencyBudgetBurn": ("ingestion-latency", "ingestion-latency-budget-burn",
                                   "Ingestion processing latency SLO (< 500 ms, REQ-A) is burning budget"),
    "ForecastErrorBudgetBurn": ("forecast-availability", "forecast-error-budget-burn",
                                "Forecast runs are failing fast enough to exhaust the error budget"),
    "ForecastLatencyBudgetBurn": ("forecast-latency", "forecast-latency-budget-burn",
                                  "Forecast latency SLO (< 2 s, REQ-D) is burning budget"),
}
obj = {s[0]: s for s in SLOS}
al = ["# GENERATED by infra/prometheus/gen_slo_rules.py (python3 infra/prometheus/gen_slo_rules.py infra/prometheus/rules) — do not edit by hand — multi-window, multi-burn-rate SLO alerts.",
      "# Page  (critical): 2% of 30d budget in 1h  (14.4x, 1h & 5m)  or 5% in 6h (6x, 6h & 30m)",
      "# Ticket (warning): 10% of 30d budget in 3d (1x, 3d & 6h)    or 10% in 1d (3x, 1d & 2h)",
      "groups:", "  - name: slo-burn-rate-alerts", "    rules:"]
for name, (slo, rb, summary) in BURN.items():
    _, svc, o, *_ = obj[slo]
    e = round(1 - o, 6)
    sel = f'{{slo="{slo}"}}'
    for sev, pairs, desc in [
        ("critical", [("1h", "5m", 14.4), ("6h", "30m", 6)], "fast burn"),
        ("warning", [("1d", "2h", 3), ("3d", "6h", 1)], "slow burn"),
    ]:
        parts = []
        for lw, sw, f in pairs:
            parts.append(f"(\n            slo:sli_error:ratio_rate{lw}{sel} > ({f} * {e})\n          and\n            slo:sli_error:ratio_rate{sw}{sel} > ({f} * {e})\n          )")
        expr = "\n          or\n          ".join(parts)
        al += [f"      - alert: {name}",
               f"        expr: |",
               f"          {expr}",
               f"        for: 2m" if sev == "critical" else f"        for: 15m",
               f"        labels:",
               f"          severity: {sev}",
               f"          service: {svc}",
               f"          slo: {slo}",
               f"        annotations:",
               f"          summary: \"{summary} ({desc})\"",
               f"          description: \"SLO {slo} (objective {o*100:g}%) error ratio is {{{{ $value | humanizePercentage }}}} — {desc}. See Grafana SLO dashboard.\"",
               f"          runbook_url: \"{RB}{rb}.md\"",
               f"          dashboard: \"http://localhost:3000/d/aiops-slo\""]
open(f"{OUT}/slo-burn-alerts.yml", "w").write("\n".join(al) + "\n")
print("ok")
